# NumPy Basics

In [3]:
import numpy as np

## Efficiency

In [14]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [11]:
np.arange(10) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [12]:
%timeit -n 1000 [x**2 for x in range(1000)]
%timeit -n 1000 np.arange(1000) ** 2

520 µs ± 8.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.35 µs ± 623 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Creating a Simple Array

In [ ]:
ls = [1,2,3,4,5]
np.array(ls)

### Getting Basic Information about an Array

In [15]:
ar = np.array([1,2,3,4,5])
ar_type = type(ar)
array_size = np.size(ar)
array_dimensions = ar.ndim
array_data_type = ar.dtype

print('''Object type: {}
Array size: {},
Array dimensions: {},
Array data type: {}'''.format(ar_type,
                              array_size,
                              array_dimensions,
                              array_data_type))

Object type: <class 'numpy.ndarray'>
Array size: 5,
Array dimensions: 1,
Array data type: int32


### np.arange()

In [16]:
ar1 = np.arange(10)
print('ar1:', ar1)

ar2 = np.arange(5,11)
print('ar2:', ar2)

ar3 = np.arange(0,13,3)
print('ar3:', ar3)

ar4 = np.arange(4,-4,-1)
print('ar4:', ar4)

ar1: [0 1 2 3 4 5 6 7 8 9]
ar2: [ 5  6  7  8  9 10]
ar3: [ 0  3  6  9 12]
ar4: [ 4  3  2  1  0 -1 -2 -3]


In [17]:
ar5 = np.arange(1,5,1)
print(ar5, type(ar5[0]))

ar6 = np.arange(1,5,.5)
print(ar6, type(ar6[0]))

ar7 = np.arange(1,5, dtype=float)
print(ar7, type(ar7[0]))

[1 2 3 4] <class 'numpy.int32'>
[1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.float64'>
[1. 2. 3. 4.] <class 'numpy.float64'>


In [18]:
ar = np.arange(1,10)
print( type(ar[0]))

ar[5] = 1.5
print( ar[5] )

<class 'numpy.int32'>
1


## Similar to Lists
ndarrays are iterators

In [20]:
ls = [x**2 for x in range(10)]
ar = np.arange(10) ** 2

for i in ls:
    print(i, end=' ')

print('\n', '-' * 25) # this just prints a separator line

for i in ar:
    print(i, end=' ')

0 1 4 9 16 25 36 49 64 81 
 -------------------------
0 1 4 9 16 25 36 49 64 81 

In [21]:
who

ar	 ar1	 ar2	 ar3	 ar4	 ar5	 ar6	 ar7	 ar_type	 
array_data_type	 array_dimensions	 array_size	 i	 ls	 np	 


## Different from Lists

### Operators that behave differently

In [22]:
ls = [1,2,3,4,5]
print(ls)
print(ls + ls) #Appends list to itself
print(ls * 2) #Repeats list twice

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [24]:
ar = np.arange(1,6)
print(ar)
print(type(ar))
print(ar + ar) #Adds ar[0] to ar[0], ar[1] to ar[1], etc.
print(ar * 2) #Multiplies each element of array by 2

[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [29]:
ar1 = np.arange(1,6)
s = 2
ls = [2,2,2,2,2]
print(type(ls))
ar2 = np.array( [2,2,2,2,2] )

print(ar1 * s)
print(ar1 * ls)
print(ar1 * ar2)

<class 'list'>
[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [31]:
ar = np.arange(1,6)
print(ar)
print(ar + 2) #Add 2 to each element of array
print(ar - 2) #Subtract 2 from each element of array
print(ar / 2) #Divide each element of array by 2
print(ar ** 2) #Square each element of array
print(ar ** .5) #Get square root of each element of array
ar += 10 #Add 10 to each element of array
print(ar)

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[11 12 13 14 15]


## Universal Functions

### Zipping two iterables

In [33]:
r1 = range(1,10)
r2 = range(10,1,-1)
z = zip(r1,r2)
z
list(z)

[(1, 10), (2, 9), (3, 8), (4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (9, 2)]

### Displaying the zip as a list

In [34]:
list(z)

[]

### Looping through zip object to create list

In [36]:
ls = []
for i1, i2 in zip(r1,r2):
    ls.append(i1 * i2)
ls

[10, 18, 24, 28, 30, 30, 28, 24, 18]

### Multiplying two nparrays

In [37]:
ar1 = np.arange(1,10)
ar2 = np.arange(10,1,-1)
np.multiply(ar1,ar2)

array([10, 18, 24, 28, 30, 30, 28, 24, 18])

### Adding array-like objects

In [54]:
ls = [1,3,5,7]
print(type(ls))
r = range(0,4)
print(type(r))
x = ls, r, np.add(ls,r)
print(type(x))
print(x)

<class 'list'>
<class 'range'>
<class 'tuple'>
([1, 3, 5, 7], range(0, 4), array([ 1,  4,  7, 10]))


### Some Examples of Universal Functions

In [39]:
ar_ints = np.arange(1,6)
ar_floats = np.arange(1,7.5,1.5)

In [40]:
np.add(ar_ints, ar_floats)

array([ 2. ,  4.5,  7. ,  9.5, 12. ])

In [41]:
np.negative(ar_ints)

array([-1, -2, -3, -4, -5])

In [42]:
np.square(ar_ints)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [43]:
np.hypot(ar_ints, ar_ints)

array([1.41421356, 2.82842712, 4.24264069, 5.65685425, 7.07106781])

In [44]:
np.greater(ar_ints, ar_floats)

array([False, False, False, False, False])

In [45]:
np.ceil(ar_floats)

array([1., 3., 4., 6., 7.])