# Random Sampling

In [2]:
import numpy as np

In [6]:
np.random.rand(2,4)

array([[0.80103969, 0.39785222, 0.06620872, 0.65811751],
       [0.1161289 , 0.07984871, 0.75497952, 0.1499627 ]])

In [7]:
np.random.randn(2,4)

array([[-0.75903043,  0.84887675,  0.16563005, -0.42665066],
       [-0.6347715 , -0.4285583 , -0.0861254 ,  0.53854966]])

In [10]:
np.random.randint(1,100, (2,4) )

array([[10,  9, 73, 15],
       [56, 24, 94, 36]])

In [12]:
xs = np.random.randint(100, size=10)
ys =  np.random.randint(100, size=10)
points = zip(xs, ys)
for point in points:
    print(point)

(51, 80)
(93, 36)
(52, 96)
(45, 8)
(67, 35)
(47, 95)
(51, 69)
(60, 8)
(51, 93)
(41, 36)


### It's Fast!

In [13]:
import random

In [14]:
%%timeit -n 1000
ar = np.random.randint(0, 100001, 1000)
np.mean(ar)

45.7 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
%%timeit -n 1000
ls = random.sample(range(100000), 1000)
sum(ls)/len(ls)

1.35 ms ± 22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
